# Generated by Django 6.0.4 on 2026-04-28 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('routes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, help_text='Генерується автоматично після збереження.', max_length=20, unique=True, verbose_name='Номер замовлення')),
                ('contact_first_name', models.CharField(max_length=64, verbose_name="Ім'я контакту")),
                ('contact_last_name', models.CharField(max_length=64, verbose_name='Прізвище контакту')),
                ('contact_phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('status', models.CharField(choices=[('pending', 'Очікує підтвердження'), ('confirmed', 'Підтверджене'), ('paid', 'Оплачене'), ('in_progress', 'Поїздка триває'), ('completed', 'Завершене'), ('cancelled', 'Скасоване'), ('refunded', 'Повернено кошти')], default='pending', max_length=15, verbose_name='Статус')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Загальна сума')),
                ('currency', models.CharField(default='EUR', max_length=3, verbose_name='Валюта')),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'Готівка'), ('card', 'Картка'), ('bank', 'Банківський переказ'), ('online', 'Онлайн')], max_length=10, verbose_name='Спосіб оплати')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Оплачено')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('customer', models.ForeignKey(blank=True, help_text='Заповнюється, якщо бронює корпоративний клієнт.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customers.customer', verbose_name='Клієнт (компанія)')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='routes.trip', verbose_name='Рейс')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Номер квитка')),
                ('passenger_first_name', models.CharField(max_length=64, verbose_name="Ім'я пасажира")),
                ('passenger_last_name', models.CharField(max_length=64, verbose_name='Прізвище пасажира')),
                ('passenger_date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('document_type', models.CharField(choices=[('passport', 'Закордонний паспорт'), ('id_card', 'ID-картка'), ('driving', 'Посвідчення водія'), ('birth', 'Свідоцтво про народження')], default='passport', max_length=10, verbose_name='Тип документа')),
                ('document_number', models.CharField(max_length=40, verbose_name='Номер документа')),
                ('passenger_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон пасажира')),
                ('seat_number', models.CharField(blank=True, max_length=10, verbose_name='Номер місця')),
                ('price_type', models.CharField(choices=[('adult', 'Дорослий'), ('child', 'Дитячий'), ('student', 'Студентський'), ('senior', 'Пенсійний'), ('disabled', 'Пільговий')], default='adult', max_length=10, verbose_name='Тип квитка')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна')),
                ('status', models.CharField(choices=[('booked', 'Заброньований'), ('paid', 'Оплачений'), ('used', 'Використаний'), ('cancelled', 'Скасований'), ('refunded', 'Повернутий')], default='booked', max_length=10, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('alighting_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alighting_tickets', to='routes.stop', verbose_name='Місце висадки')),
                ('boarding_stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boarding_tickets', to='routes.stop', verbose_name='Місце посадки')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='orders.order', verbose_name='Замовлення')),
            ],
            options={
                'verbose_name': 'Квиток',
                'verbose_name_plural': 'Квитки',
                'ordering': ['-created_at'],
            },
        ),
    ]
