# Generated by Django 6.0.4 on 2026-04-29 13:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Код')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Опис')),
                ('discount_percent', models.PositiveSmallIntegerField(help_text='Відсоток знижки від суми замовлення', verbose_name='Знижка, %')),
                ('valid_from', models.DateField(default=django.utils.timezone.now, verbose_name='Діє з')),
                ('valid_until', models.DateField(verbose_name='Діє до')),
                ('usage_limit', models.PositiveIntegerField(default=0, help_text='0 = без обмежень', verbose_name='Ліміт використань')),
                ('times_used', models.PositiveIntegerField(default=0, verbose_name='Використано разів')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоди',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Сума знижки'),
        ),
        migrations.AddField(
            model_name='order',
            name='promo_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.promocode', verbose_name='Промокод'),
        ),
    ]
