# Generated by Django 6.0.4 on 2026-05-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_created_f0ce29_idx',
            old_name='orders_orde_created_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_079368_idx',
            old_name='orders_orde_status_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_trip_id_d4cea0_idx',
            old_name='orders_orde_trip_st_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='orders_tick_order_i_1dd287_idx',
            old_name='orders_tick_order_st_idx',
        ),
    ]
