# Generated by Django 6.0.4 on 2026-05-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_rename_orders_orde_created_idx_orders_orde_created_f0ce29_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='loyalty_awarded_at',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Дата коли клієнту нараховано бонусні бали за це замовлення.', null=True, verbose_name='Бали нараховано'),
        ),
    ]
