# Generated by Django 6.0.4 on 2026-04-28 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва (комерційна)')),
                ('legal_name', models.CharField(blank=True, max_length=255, verbose_name='Юридична назва')),
                ('tax_number', models.CharField(blank=True, max_length=32, verbose_name='ЄДРПОУ / податковий номер')),
                ('vat_number', models.CharField(blank=True, max_length=32, verbose_name='VAT номер (для іноземних)')),
                ('country', models.CharField(choices=[('UA', 'Україна'), ('PL', 'Польща'), ('DE', 'Німеччина'), ('SK', 'Словаччина'), ('HU', 'Угорщина'), ('RO', 'Румунія'), ('CZ', 'Чехія'), ('AT', 'Австрія'), ('IT', 'Італія'), ('FR', 'Франція'), ('XX', 'Інша')], default='UA', max_length=2, verbose_name='Країна')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Місто')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Юридична адреса')),
                ('contact_person', models.CharField(blank=True, max_length=150, verbose_name='Контактна особа')),
                ('contact_phone', models.CharField(blank=True, max_length=30, verbose_name='Телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('payment_terms_days', models.PositiveSmallIntegerField(default=14, verbose_name='Відстрочка оплати, днів')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
                ('portal_user', models.OneToOneField(blank=True, help_text='Користувач з роллю «Клієнт», який має доступ до кабінету.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='Кабінет клієнта (користувач)')),
            ],
            options={
                'verbose_name': 'Клієнт',
                'verbose_name_plural': 'Клієнти',
                'ordering': ['name'],
            },
        ),
    ]
