# Generated by Django 6.0.4 on 2026-05-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='loyalty_points',
            field=models.PositiveIntegerField(default=0, help_text='1 бал = 1 EUR знижки. Нараховуються після завершення поїздки.', verbose_name='Бонусних балів'),
        ),
    ]
