# Generated by Django 6.0.4 on 2026-04-29 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('action', models.CharField(choices=[('create', 'Створено'), ('update', 'Змінено'), ('delete', 'Видалено')], max_length=10, verbose_name='Дія')),
                ('model_name', models.CharField(max_length=100, verbose_name='Модель')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name="ID об'єкта")),
                ('object_repr', models.CharField(max_length=200, verbose_name="Назва об'єкта")),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='Зміни')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Запис аудиту',
                'verbose_name_plural': 'Аудит-журнал',
                'ordering': ['-timestamp'],
            },
        ),
    ]
