# Generated by Django 6.0.4 on 2026-04-28 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Внутрішній код, напр. UA-CZ-001', max_length=20, unique=True, verbose_name='Код маршруту')),
                ('name', models.CharField(help_text='Напр.: Ужгород - Прага', max_length=200, verbose_name='Назва')),
                ('origin_country', models.CharField(max_length=2, verbose_name='Країна відправлення')),
                ('origin_city', models.CharField(max_length=100, verbose_name='Місто відправлення')),
                ('destination_country', models.CharField(max_length=2, verbose_name='Країна призначення')),
                ('destination_city', models.CharField(max_length=100, verbose_name='Місто призначення')),
                ('distance_km', models.PositiveIntegerField(verbose_name='Відстань, км')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Орієнтовна тривалість поїздки у хвилинах', verbose_name='Тривалість, хв')),
                ('description', models.TextField(blank=True, verbose_name='Опис')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Маршрут',
                'verbose_name_plural': 'Маршрути',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_at', models.DateTimeField(verbose_name='Час відправлення')),
                ('status', models.CharField(choices=[('planned', 'Запланований'), ('on_sale', 'У продажу'), ('in_progress', 'У дорозі'), ('completed', 'Завершений'), ('cancelled', 'Скасований')], default='planned', max_length=15, verbose_name='Статус')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Базова ціна квитка')),
                ('currency', models.CharField(choices=[('UAH', 'грн'), ('EUR', '€'), ('USD', '$'), ('PLN', 'zł')], default='EUR', max_length=3, verbose_name='Валюта')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('co_driver', models.ForeignKey(blank=True, limit_choices_to={'is_available': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips_as_co', to='fleet.driver', verbose_name='Змінний водій')),
                ('main_driver', models.ForeignKey(limit_choices_to={'is_available': True}, on_delete=django.db.models.deletion.PROTECT, related_name='trips_as_main', to='fleet.driver', verbose_name='Основний водій')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='routes.route', verbose_name='Маршрут')),
                ('vehicle', models.ForeignKey(limit_choices_to={'is_active': True, 'vehicle_type__in': ['bus', 'minibus', 'van']}, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='fleet.vehicle', verbose_name='Транспортний засіб')),
            ],
            options={
                'verbose_name': 'Рейс',
                'verbose_name_plural': 'Рейси',
                'ordering': ['-departure_at'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='1, 2, 3... за порядком руху', verbose_name='№ у маршруті')),
                ('country', models.CharField(max_length=2, verbose_name='Країна')),
                ('city', models.CharField(max_length=100, verbose_name='Місто')),
                ('station_name', models.CharField(blank=True, max_length=200, verbose_name='Автостанція')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Адреса')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Довгота')),
                ('arrival_offset_minutes', models.PositiveIntegerField(default=0, verbose_name='Прибуття від старту, хв')),
                ('departure_offset_minutes', models.PositiveIntegerField(default=0, verbose_name='Відправлення від старту, хв')),
                ('can_board', models.BooleanField(default=True, verbose_name='Посадка')),
                ('can_alight', models.BooleanField(default=True, verbose_name='Висадка')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.route', verbose_name='Маршрут')),
            ],
            options={
                'verbose_name': 'Зупинка',
                'verbose_name_plural': 'Зупинки',
                'ordering': ['route', 'order'],
                'unique_together': {('route', 'order')},
            },
        ),
    ]
