# Generated by Django 6.0.4 on 2026-05-15 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='trip',
            new_name='routes_trip_status_efa9fe_idx',
            old_name='routes_trip_status_dep_idx',
        ),
        migrations.RenameIndex(
            model_name='trip',
            new_name='routes_trip_route_i_6a4c79_idx',
            old_name='routes_trip_route_dep_idx',
        ),
    ]
