# Generated by Django 6.0.4 on 2026-04-28 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bus', 'Автобус'), ('minibus', 'Мікроавтобус'), ('van', 'Мікровен'), ('truck', 'Вантажівка'), ('trailer', 'Причіп')], default='bus', max_length=10, verbose_name='Тип ТЗ')),
                ('registration_number', models.CharField(max_length=20, unique=True, verbose_name='Номерний знак')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Рік випуску')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='VIN')),
                ('color', models.CharField(blank=True, max_length=30, verbose_name='Колір')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Дизель'), ('petrol', 'Бензин'), ('gas', 'Газ'), ('electric', 'Електро'), ('hybrid', 'Гібрид')], default='diesel', max_length=10, verbose_name='Паливо')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='vehicles/', verbose_name='Фото')),
                ('mileage_km', models.PositiveIntegerField(default=0, verbose_name='Пробіг, км')),
                ('date_acquired', models.DateField(blank=True, null=True, verbose_name='Дата придбання')),
                ('insurance_expiry', models.DateField(blank=True, null=True, verbose_name='Страховка до')),
                ('last_inspection_date', models.DateField(blank=True, null=True, verbose_name='Останній техогляд')),
                ('next_inspection_date', models.DateField(blank=True, null=True, verbose_name='Наступний техогляд')),
                ('seats_total', models.PositiveSmallIntegerField(blank=True, help_text='Тільки для автобусів та мікроавтобусів.', null=True, verbose_name='Кількість пасажирських місць')),
                ('comfort_class', models.CharField(blank=True, choices=[('economy', 'Економ'), ('tourist', 'Турист'), ('business', 'Бізнес'), ('luxury', 'Люкс')], max_length=10, verbose_name='Клас комфорту')),
                ('has_wifi', models.BooleanField(default=False, verbose_name='Wi-Fi')),
                ('has_wc', models.BooleanField(default=False, verbose_name='Туалет')),
                ('has_climate', models.BooleanField(default=False, verbose_name='Клімат-контроль')),
                ('has_tv', models.BooleanField(default=False, verbose_name='ТВ / мультимедіа')),
                ('has_usb', models.BooleanField(default=False, verbose_name='USB-розетки')),
                ('luggage_volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Об'єм багажника, м³")),
                ('capacity_tons', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Вантажопідйомність, т')),
                ('volume_m3', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name="Об'єм кузова, м³")),
                ('is_active', models.BooleanField(default=True, verbose_name='В експлуатації')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Оновлено')),
            ],
            options={
                'verbose_name': 'Транспортний засіб',
                'verbose_name_plural': 'Транспортні засоби',
                'ordering': ['vehicle_type', 'registration_number'],
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_number', models.CharField(max_length=30, verbose_name='Номер посвідчення')),
                ('license_categories', models.CharField(help_text='Через кому, напр.: B, C, CE, D, D1', max_length=50, verbose_name='Категорії')),
                ('license_expiry', models.DateField(verbose_name='Посвідчення дійсне до')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('date_of_hire', models.DateField(blank=True, null=True, verbose_name='Дата прийому на роботу')),
                ('nationality', models.CharField(blank=True, max_length=50, verbose_name='Громадянство')),
                ('passport_number', models.CharField(blank=True, max_length=30, verbose_name='Номер закордонного паспорта')),
                ('passport_expiry', models.DateField(blank=True, null=True, verbose_name='Паспорт дійсний до')),
                ('medical_check_expiry', models.DateField(blank=True, null=True, verbose_name='Медогляд до')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступний для рейсів')),
                ('notes', models.TextField(blank=True, verbose_name='Примітки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Створено')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='driver_profile', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Водій',
                'verbose_name_plural': 'Водії',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
    ]
